### ISSUE TITLE
Add examples to R documentation (JOSS review)

### ISSUE THREAD

**Issue by gavinsimpson** [wilsoncai1992/adaptest#12]
User-facing functions in an R package should have an Examples section indicating how the function is used and some of the functionality. In addition, packages authors might include a vignette which acts as documentation, often in tutorial form, that illustrates in a practical sense how the package works.

I can't sign off on this element (openjournals/joss-reviews#161):

> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

currently as none of the Rd pages have examples and/or there is no vignette or other associated documentation that fills this criterion.

**Comment by wilsoncai1992** [comment]
Dear @gavinsimpson,

Thank you so much for pointing out! We have some tutorials at hand and will start putting up a vignette immediately.

**Comment by gavinsimpson** [comment]
It requires more than a vignette; Writing R Extensions, as well as conventions in the R world require that user-facing functions should all have an `\examples{}` section in the Rd file with example code that illustrates how to use said function.
