### ISSUE TITLE
JOSS Review: unit tests should cover all of the package functions

### ISSUE THREAD

**Issue by gavinsimpson** [wilsoncai1992/adaptest#16]
The only unit tests in the package currently current is a single test of the `data_adapt()` function, which tests if the function fails if called incorrectly. As such there are no tests to confirm the functions in the package work as expected.

Please add unit tests that test all functions in the package, especially that the functions work as intended, rather than only failing with incorrect inputs.

openjournals/joss-reviews/issues/161

**Comment by nhejazi** [comment]
We believe this has been resolved as of bb90fa5, the latest commit on the version of this package accepted into and released with Bioconductor 3.7, available at https://github.com/wilsoncai1992/adaptest/tree/RELEASE_3_7
