### ISSUE TITLE
cross-validation with origami

### ISSUE THREAD

**Issue by nhejazi** [wilsoncai1992/adaptest#22]
Jeremy's [new `origami` package](https://github.com/jeremyrcoyle/origami) provides machinery to very easily generate learning and estimation samples from an input object, like a `data.frame`. Using this tool (in particular, the function `origami::make_folds`) might be a nice way to easily structure samples for use with the data-adaptive multiple testing scheme.

The package is already on CRAN, thus making it a valid dependency when we submit this package to Bioconductor.

**Comment by wilsoncai1992** [comment]
complete
