### ISSUE TITLE
Release versions

### ISSUE THREAD

**Issue by kellieotto** [wilsoncai1992/adaptest#47]
For your JOSS Review:

The DESCRIPTION file states that the version is 1.1.0 whereas the Github release version is 0.2.0. Then, when I loaded the package into R it printed the message "adaptest v1.0.0: Data-Adaptive Statistics for High-Dimensional Multiple Testing". Must be the version available on Bioconductor? Make sure the versions are consistent everywhere!

**Comment by nhejazi** [comment]
Thanks for pointing this out! We hadn't noticed this inconsistency and agree that this is horribly confusing. The GitHub releases/ git tags have been fixed to match Biooconductor releases, and a note has been added to the README (as of #53) to clarify that `master` is in fact the development branch. Closing this but please feel free to re-open if I missed something.

**Comment by kellieotto** [comment]
Looks good.
