### ISSUE TITLE
Example website

### ISSUE THREAD

**Issue by kellieotto** [wilsoncai1992/adaptest#49]
For your JOSS Review:

Link to your Bioconductor vignette website at the top of the Github repo -- make it really easy to find.

In vignette section 0.2, I run the code and look at `adaptest_out`. I think you just need to clarify language here. There are more attributes than the ones you've listed. Additionally the data type of `adaptest_out` is different:

```
> class(adaptest_out)
[1] "data_adapt"
```

As someone who's never used TMLE, I think it might be helpful to describe a bit about what's going on behind the scenes or link to existing documentation for these methods.

**Comment by nhejazi** [comment]
Thanks for pointing this out @kellieotto! It seems like we neglected to update the package vignette after making some fairly significant internal changes. I've just addressed these issues in #56, which correctly states the name of the class as `data_adapt`, clarifies that the 9 slots listed in the vignette are those that would be of user interest (noting others contain auxiliary information that ought be ignored), and further discussing the `summary` method that users should rely on.

We've also taken the opportunity to point to manuscripts that describe the definition and use of data-adaptive target parameters in general, including our arxiv paper and the previous work on which it builds. Given the target audience, I think that a description of TMLE might be outside of the scope of the vignette and so I've added notes pointing to other resources. Additionally, I just want to note that these changes won't be reflected on Bioconductor until their next release (next month), but the `pkgdown` site https://wilsoncai1992.github.io/adaptest will immediately reflect these updates to the vignette. Lastly, we've added some Bioconductor badges to the top of the README to allow users to easily navigate to the Bioconductor page of the package. I will close this after merging #56, but please feel free to re-open if we can do a bit more on this front.
