### ISSUE TITLE
JOSS paper recommendations

### ISSUE THREAD

**Issue by kellieotto** [wilsoncai1992/adaptest#50]
For your JOSS Review:

You make it clear in the first few paragraphs what problem the package is solving, but the example you include doesn't quite convey the point. If I understand correctly, the goal is to pick out which features have the greated association with some outcome. In the example, this outcome isn't described. I'd like to better understand what the plot is showing as well -- for each fold of CV, you rank the covariates according to strength of association, then you plot the average rank? I think this can be fixed with a few descriptive sentences. 

Don't use language like "it is clear" (in the following paragraph); it wasn't clear to me right away. Just describe what the reader should notice and what it means. 

Refer to plots by reference (Figure 1, 2) rather than "figure above/below".

**Comment by wilsoncai1992** [comment]
Dear @kellieotto, 
Thank you for your kind review! The JOSS paper has been improved and all your suggestions are addressed in #57

**Comment by kellieotto** [comment]
👍
