### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by kellieotto** [wilsoncai1992/adaptest#51]
For your JOSS review:

I'm really glad to see you're using Travis CI and a coverage metric for your code! There are missing unit tests for some of your functions; this page shows that some files have 0% test coverage. https://codecov.io/github/wilsoncai1992/adaptest?branch=master Some of the files look like they're just utility functions. Please add tests or explain briefly why a test isn't necessary (e.g. if it's just a printing/summary function).

**Comment by nhejazi** [comment]
Thanks for pointing this out. We've amended this by either adding new unit tests or ignoring the relevant files from the coverage check done by `codecov` (https://codecov.io/gh/wilsoncai1992/adaptest/tree/master/R). I attempt to provide explanations for these choices below

* For the constructor function `.adaptmle` of the S4 class we introduce, there now exists a unit test to check that class inheritance is performed correctly.
* Contents of the files 'utils.R', 'get_summary.R', 'data.R', and 'bioadaptest.R' are all now ignored for the following reasons
  * 'utils.R' simply contains simple printing/summary functions.
  * 'get_summary.R' contains a printing/accessor function that could have also been organized under 'utils.R'.
  * 'data.R' simply provides documentation for two simulated data sets included in the package.
  * 'bioadaptest.R' includes a user-facing wrapper function that is simply a call to the core function `adaptest` (which has corresponding unit tests). The extra lines in this function extract relevant objects from an input `SummarizedExperiment`, pass them to `adaptest`, and construct an output object to pass back to the user. There's no additional functionality to be tested here.

At this time, I believe the unit tests are sufficient to cover core functionality exposed by the package --- that said, there's always room for improvement (by tightening up tests, perhaps down the road). I will close this issue, but please feel free to re-open should there remain any items unaddressed.

**Comment by kellieotto** [comment]
Thanks for clarifying! This is all fine by me.
