### ISSUE TITLE
JOSS Paper reference DOIs

### ISSUE THREAD

**Issue by kellieotto** [wilsoncai1992/adaptest#52]
For your JOSS review:

Go back and make sure all your references have a DOI.

**Comment by kellieotto** [comment]
I thought I found a DOI for the FDR paper (DOI: 10.2307/2346101). It works when you google it, but if you search it on the actual doi.org, it doesn't come up. Weird. I'll go ahead and close the issue.

**Comment by wilsoncai1992** [comment]
ninja land on the master branch has incorporated your DOI suggestion
